spring:

  datasource:
    url: jdbc:postgresql://localhost:5435/matrix_api_db
    username: admin
    password: admin

  jpa:
    show-sql: true
    properties:
      hibernate.generate_statistics: true