server:
  port: 8085

spring:

  profiles:
    active: ${ENVIRONMENT:dev}

  liquibase:
    enabled: true
    change-log: classpath:/db/db.changelog-master.xml

  datasource:
    url:
    username:
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: false
    properties:
      hibernate.generate_statistics: false
